// English-source → Japanese translations for UI chrome.
//
// Keys are the exact English strings passed to `ts(...)`. Any string missing
// here falls back to its English source automatically, so partial coverage is
// always safe. AI-generated study content (flashcard fronts/backs, note bodies,
// quiz questions) is intentionally NOT translated here — only the app's own UI.
//
// Interpolation: use {name} placeholders in both the English source and the
// Japanese value, e.g. ts('Scored {p}%', { p: 80 }).

export const ja: Record<string, string> = {
  // ── Navigation / chrome ───────────────────────────────────────────────────
  'Dashboard': 'ダッシュボード',
  'Mind Map': 'マインドマップ',
  'Flashcards': 'フラッシュカード',
  'Notes': 'ノート',
  'Note': 'ノート',
  'Quiz': 'クイズ',
  'Generate': '生成',
  'Manage': '管理',
  'Language': '言語',
  'Japanese': '日本語',
  'English': '英語',
  'Both': '両方',
  'Switch to {label}': '{label}に切り替え',
  'Study Trainer': 'スタディトレーナー',
  'Global Business Studies': 'グローバルビジネス学習',
  'Open menu': 'メニューを開く',
  'Close menu': 'メニューを閉じる',

  // ── Cloud status / dim / toast ────────────────────────────────────────────
  'Firebase (notes/flashcards/quizzes) and Supabase (file storage) are not configured.':
    'Firebase（ノート／フラッシュカード／クイズ）と Supabase（ファイルストレージ）が設定されていません。',
  'Firebase is not configured — notes, flashcards and quizzes will not be shared.':
    'Firebase が設定されていません — ノート、フラッシュカード、クイズは共有されません。',
  'Supabase is not configured — uploaded files will not be shared.':
    'Supabase が設定されていません — アップロードしたファイルは共有されません。',
  'Local-only mode': 'ローカルのみモード',
  'Dismiss': '閉じる',
  'Hide': '非表示',
  // ── Home / dashboard ──────────────────────────────────────────────────────
  'Cards': 'カード',
  'Explore': '見る',
  'Globe': 'グローブ',
  'Good morning.': 'おはようございます。',
  'Good afternoon.': 'こんにちは。',
  'Good evening.': 'こんばんは。',
  'Click a subject on the globe to dive in.': 'グローブ上の科目をクリックして始めましょう。',
  'Scroll': 'スクロール',
  'You have {cards} due for review across {subjects}.':
    '{subjects}にわたって復習予定の{cards}があります。',
  '{n} subjects': '{n} 科目',
  '{n} due': '復習予定 {n} 件',
  'Review': '復習',
  'Upcoming Exams': '今後の試験',
  '{n} days left': '残り {n} 日',
  'Today': '今日',
  '{n} days ago': '{n} 日前',
  'Continue where you left off': '続きから学習する',
  'Resume': '再開',
  'Remove {name} from recents': '{name} を最近の項目から削除',
  '{n} cards': '{n} カード',
  '{n} notes': '{n} ノート',
  '{n} questions': '{n} 問題',
  'AI powered': 'AI搭載',
  'No core subjects. Star one in': '主要科目がありません。次でスター登録してください:',

  // ── Built-in subject titles ───────────────────────────────────────────────
  'International Trade': '国際貿易',
  'Marketing': 'マーケティング',
  'Finance': 'ファイナンス',
  'Economics': '経済学',
  'Chinese': '中国語',
  'Research for Business Studies': 'ビジネス研究法',
  'English for Qualifications and Practical communication': '資格・実践コミュニケーション英語',
  'Business Economics': 'ビジネス経済学',
  'Pre Seminar': 'プレゼミ',
  'Accounting Advanced': '上級会計',
  'Management': '経営学',

  // ── Built-in subject descriptions ─────────────────────────────────────────
  'Comparative advantage, trade policy, Heckscher-Ohlin, terms of trade.':
    '比較優位、貿易政策、ヘクシャー＝オリーン、交易条件。',
  'Marketing mix, segmentation, brand equity, consumer behaviour.':
    'マーケティングミックス、セグメンテーション、ブランドエクイティ、消費者行動。',
  'NPV, IRR, WACC, capital markets, EMH, risk and return.':
    'NPV、IRR、WACC、資本市場、効率的市場仮説、リスクとリターン。',
  'Elasticity, GDP, monetary policy, game theory and market structures.':
    '弾力性、GDP、金融政策、ゲーム理論、市場構造。',
  'Japanese language studies: grammar, vocabulary and kanji.':
    '日本語学習：文法、語彙、漢字。',
  'Mandarin Chinese language studies: grammar, vocabulary and hanzi.':
    '中国語（標準語）学習：文法、語彙、漢字。',
  'Research methods, methodology, data collection and analysis.':
    '研究手法、方法論、データ収集と分析。',
  'English for academic qualifications and practical, real-world communication.':
    '学術資格と実践的な実世界コミュニケーションのための英語。',
  'Applied economics: business cycles, fiscal policy, exchange rates.':
    '応用経済学：景気循環、財政政策、為替レート。',
  'Academic writing, research skills, presentation and citation.':
    'アカデミックライティング、研究スキル、プレゼンテーション、引用。',
  'Advanced financial reporting, consolidation, IFRS standards.':
    '上級財務報告、連結、IFRS基準。',
  'Managerial theory, organisational behaviour, leadership and change.':
    '経営理論、組織行動、リーダーシップと変革。',
  'Level 1': 'レベル1',
  'Level 2': 'レベル2',
  'Level 3': 'レベル3',

  // ── Subject page / sidebar ────────────────────────────────────────────────
  'Content': 'コンテンツ',
  'Files': 'ファイル',
  'Unfiled': '未整理',
  'Overview': '概要',
  'Dictionary': '辞書',
  'Quizzes': 'クイズ',
  'Flashcard sets': 'フラッシュカードセット',
  'None yet': 'まだありません',
  'None': 'なし',
  'Level': 'レベル',
  'Core': '主要',
  'Extended': '拡張',
  'Core subject': '主要科目',
  'Make core': '主要に設定',
  'Make extended': '拡張に設定',
  'Add subject': '科目を追加',
  'New subject': '新しい科目',
  'Edit subject': '科目を編集',
  'Delete subject': '科目を削除',
  'Manage subjects': '科目を管理',
  'Subject name': '科目名',
  'Subject title': '科目タイトル',
  'Subject context': '科目のコンテキスト',
  'Subject dashboard': '科目ダッシュボード',
  'Subject not found': '科目が見つかりません',
  'Unknown subject': '不明な科目',
  'Short description': '短い説明',
  'Short description (optional)': '短い説明（任意）',
  'Icon': 'アイコン',
  'Settings': '設定',
  'Save changes': '変更を保存',
  'Cancel': 'キャンセル',
  'Delete': '削除',
  'Change': '変更',
  'Edit names and icons, star to mark as core, create new, or remove.': '名前やアイコンを編集、スターで主要登録、新規作成または削除。',
  'Restore default subjects': 'デフォルト科目を復元',
  'No subjects. Create one below.': '科目がありません。下に作成してください。',
  'a subject': '科目',

  // ── Files ─────────────────────────────────────────────────────────────────
  'Add Files': 'ファイルを追加',
  'Upload files': 'ファイルをアップロード',
  'Upload PDFs or images to begin': '開始するにはPDFまたは画像をアップロード',
  'Upload a file and use AI to generate flashcards, notes, or a quiz.': 'ファイルをアップロードし、AIを使ってフラッシュカード・ノート・クイズを生成してください。',
  'Upload files to a subject and generate flashcards from the subject page.': '科目にファイルをアップロードし、科目ページからフラッシュカードを生成してください。',
  'Upload files to a subject and generate notes from the subject page.': '科目にファイルをアップロードし、科目ページからノートを生成してください。',
  'Upload files to a subject and generate quizzes from the subject page.': '科目にファイルをアップロードし、科目ページからクイズを生成してください。',
  'No files yet': 'ファイルがありません',
  'Only PDF and image files are supported.': 'PDFおよび画像ファイルのみサポートされています。',
  'Remove file': 'ファイルを削除',
  'Rename file': 'ファイル名を変更',
  'Download file': 'ファイルをダウンロード',
  'Image': '画像',
  '{n} PDFs': '{n} PDF',
  '{n} images': '{n} 画像',
  '{n} MB total': '合計 {n} MB',
  '{n} uploaded': '{n} 件アップロード済み',
  '{n} files added': '{n} ファイルを追加しました',
  '{n} files not shared': '{n} ファイルは共有されていません',
  '{n} files skipped': '{n} ファイルをスキップしました',
  '{n} more files': 'さらに {n} ファイル',
  '+ {n} more': 'さらに {n} 件',
  'Uploaded to the shared library.': '共有ライブラリにアップロードしました。',
  'Cloud upload failed. Saved locally only.': 'クラウドへのアップロードに失敗しました。ローカルのみに保存されました。',

  // ── Folders ───────────────────────────────────────────────────────────────
  'New folder': '新しいフォルダ',
  'Delete folder': 'フォルダを削除',
  'Folder name…': 'フォルダ名…',
  'Empty — drag items here.': '空 — ここにアイテムをドラッグ。',
  'Drop onto a folder to organise, or onto "Unfiled" to remove.': 'フォルダにドロップして整理、または「未整理」にドロップして移動。',
  '{n} folders': '{n} フォルダ',

  // ── Notes ─────────────────────────────────────────────────────────────────
  'All notes': '全ノート',
  'No notes yet': 'ノートがありません',
  'No notes yet — Generate →': 'ノートがありません — 生成 →',
  'Rename note': 'ノート名を変更',
  'Delete note': 'ノートを削除',
  'Read more': 'もっと読む',
  'Show less': '少なく表示',
  'TL;DR': '要約',
  'Contents': '目次',
  'Table of contents': '目次',
  'Close contents': '目次を閉じる',
  'Open contents': '目次を開く',
  'Navigate sections with': 'セクション移動：',
  'navigate': '移動',
  'to reveal': '表示するには',
  'Full focus': 'フルフォーカス',
  'Exit full focus': 'フルフォーカスを終了',
  'Focus': 'フォーカス',
  'Focused': '集中',
  'Hide recall': '再現テストを隠す',
  'Can you explain:': '次を説明できますか：',
  'Reveal key points': 'キーポイントを表示',
  'Mark as not understood': '理解していないとしてマーク',
  '{pct}% understood': '{pct}% 理解済み',
  '{count} Sections': '{count} セクション',
  '{n} sections': '{n} セクション',
  '~{min} min read': '約 {min} 分で読了',
  'updated {time}': '{time} に更新',
  'Read "{note}" in {subject}': '{subject} の「{note}」を読む',
  'Go to Flashcards': 'フラッシュカードへ',
  'Collapse all': 'すべて折りたたむ',
  'Expand all': 'すべて展開',
  'Reset view': '表示をリセット',
  'Ask about this content…': 'このコンテンツについて質問する…',
  'Ask a question': '質問する',
  'Thinking…': '考え中…',
  'Send': '送信',

  // ── Flashcards ────────────────────────────────────────────────────────────
  'All flashcards': '全フラッシュカード',
  'No flashcard sets yet': 'フラッシュカードセットがありません',
  'Rename flashcard set': 'フラッシュカードセット名を変更',
  'Delete flashcard set': 'フラッシュカードセットを削除',
  'Rename set': 'セット名を変更',
  'Flip card': 'カードをめくる',
  'Showing question — click to reveal answer': '問題を表示 — クリックで答えを表示',
  'Showing answer — click to flip back': '答えを表示 — クリックで戻る',
  'Next card': '次のカード',
  'Previous card': '前のカード',
  'Next →': '次へ →',
  '← Prev': '← 前へ',
  '← Back to list': '← 一覧に戻る',
  'Select all': 'すべて選択',
  '{count} Flashcards': '{count} フラッシュカード',
  'in {n} sets': '{n} セット中',
  '{n} set{s}': '{n} セット',
  'How well did you recall this?': 'このカードをどれほど思い出せましたか？',
  'Rate {label}': '{label} を評価',
  'Best': '最高',
  'Excellent': '優秀',
  'Good job': 'よくできました',
  'Decent': 'まあまあ',
  'Keep studying': '学習を続ける',
  'Wrong': '間違い',
  'You reviewed {n} card{s}. Schedule updated.': '{n} 枚のカードを復習しました。スケジュールが更新されました。',
  '{n} reviewed this session': 'このセッションで {n} 件復習しました',
  'Practice session — this result has not been saved': '練習セッション — この結果は保存されていません',
  'Practice complete': '練習完了',
  'Practice again': 'もう一度練習',
  'Review complete': '復習完了',
  'Review again': 'もう一度復習',
  'Session complete': 'セッション完了',
  'Begin': '開始',
  'Mode': 'モード',
  'Shuffle questions': '問題をシャッフル',
  'Start rated quiz': '評価クイズを開始',

  // ── Quizzes ───────────────────────────────────────────────────────────────
  'All quizzes': '全クイズ',
  'No quizzes yet': 'クイズがありません',
  'Rename quiz': 'クイズ名を変更',
  'Delete quiz': 'クイズを削除',
  'Previous quizzes': '過去のクイズ',
  'Past Results': '過去の結果',
  'Quiz complete': 'クイズ完了',
  'New test': '新しいテスト',
  'Question': '問題',
  'Questions': '問題',
  'Answer': '答え',
  'Question {n} of {total}': '{total} 問中 {n} 問目',
  'Question breakdown': '問題の詳細',
  '{count} Questions': '{count} 問題',
  '{n} quiz': '{n} クイズ',
  '{n} quizzes': '{n} クイズ',
  '{n} saved': '{n} 件保存済み',
  '{n} correct': '{n} 正解',
  '{n} still incorrect': 'まだ {n} 問不正解',
  '{n} attempts': '{n} 回試行',
  'in {n} quizzes': '{n} クイズ中',
  'CORRECT': '正解',
  'INCORRECT': '不正解',
  'Correct': '正解',
  'Correct:': '正解：',
  'Incorrect — correct: {answer}': '不正解 — 正解：{answer}',
  'Your answer:': 'あなたの答え：',
  'All correct! Great improvement.': '全問正解！素晴らしい上達です。',
  'See Results': '結果を見る',
  'Show answer': '答えを表示',
  'Show all {n} questions': '{n} 問をすべて表示',
  'Back to results': '結果に戻る',
  'Back to subject': '科目に戻る',
  'Retry': '再試行',
  'Retry same questions': '同じ問題を再試行',
  'Redo wrong answers': '間違えた答えをやり直す',
  'Redo wrong →': '間違いをやり直す →',
  'Redo remaining': '残りをやり直す',
  'Review mode — {total} missed question': '復習モード — {total} 問間違えました',
  'Review mode — {total} missed questions': '復習モード — {total} 問間違えました',
  'questions available': '利用可能な問題',
  '{answered} / {total} answered': '{total} 中 {answered} 回答済み',
  '{score} / {total} correct': '{score} / {total} 正解',
  'Scored {percent}% on {name} quiz': '{name} クイズで {percent}% を獲得',
  'Average': '平均',
  'Time': '時間',
  'Completed in': '完了時間',
  'Ready to study': '学習の準備ができました',
  'Test yourself': '自己テスト',
  'Test your Knowledge →': '知識をテスト →',
  'on {date}': '{date} に',
  'No save': '保存しない',
  'Got it': '了解',
  'Next': '次へ',
  'Prev': '前へ',

  // ── Generate ──────────────────────────────────────────────────────────────
  'Generate Study Materials': '学習素材を生成',
  'AI Generator': 'AI生成ツール',
  'Topic': 'トピック',
  'Enter a topic above to generate study materials': '上のトピックを入力して学習素材を生成',
  'Type any topic and Gemini will build flashcards, structured notes, or a quiz.': 'トピックを入力すると、Gemini がフラッシュカード・ノート・クイズを作成します。',
  'Search topics…': 'トピックを検索…',
  'optional': '任意',
  'Generating...': '生成中...',
  'Generating definition…': '定義を生成中…',
  'Generation failed': '生成に失敗しました',
  'Generated from {n} files.': '{n} ファイルから生成しました。',
  '{type} ready': '{type} 完成',
  '{n} terms': '{n} 用語',

  // ── Dictionary ────────────────────────────────────────────────────────────
  'Add to dictionary': '辞書に追加',
  'Define': '定義',
  'No dictionary entries yet': '辞書にエントリがありません',
  'No entries match "{q}"': '「{q}」に一致するエントリがありません',
  'Select a word or phrase in any note, then tap the dictionary button to add it here with an AI-generated definition.': 'ノート内の単語やフレーズを選択し、辞書ボタンをタップするとAI生成の定義とともにここに追加されます。',
  'By source': 'ソース別',
  'No source': 'ソースなし',
  'Search terms…': '用語を検索…',

  // ── Annotations ───────────────────────────────────────────────────────────
  'Highlight {color}': 'ハイライト {color}',
  'Colour': '色',
  'Colour {name}': '色 {name}',
  'Color {name}': '色 {name}',
  'Underline': '下線',

  // ── All subjects page ─────────────────────────────────────────────────────
  'All subjects': '全科目',
  '{count} topic': '{count} トピック',
  '{count} topics': '{count} トピック',
  '{n}/{total} selected': '{total} 中 {n} 選択済み',
  'No content yet': 'コンテンツがありません',

  // ── Sidebar / navigation ──────────────────────────────────────────────────
  'Collapse sidebar': 'サイドバーを折りたたむ',
  'Show sidebar': 'サイドバーを表示',
  'Streak': '連続学習',
  'Exam Date': '試験日',
  'Yesterday': '昨日',
  'Open {name}': '{name} を開く',
  'Clear': 'クリア',
  'Clear search': '検索をクリア',
  'Close': '閉じる',

  // ── Misc ──────────────────────────────────────────────────────────────────
  'Select a word or phrase': '単語やフレーズを選択',
};
